# Generated by Django 3.0.3 on 2021-03-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210311_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='desired_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
