# Generated by Django 3.0.3 on 2021-03-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210312_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
