# Generated by Django 3.0.3 on 2021-03-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_newtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newtable',
        ),
    ]
