# Generated by Django 3.0.3 on 2021-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_delete_newtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
