# Generated by Django 3.0.3 on 2021-03-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='user_fav', to='auctions.Listings'),
        ),
    ]
