# Generated by Django 3.0.3 on 2021-03-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210312_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='listing',
            field=models.ManyToManyField(blank=True, to='auctions.Listings'),
        ),
    ]
