# Generated by Django 3.0.3 on 2021-03-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210312_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
