# Generated by Django 3.2 on 2021-05-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_watchlist_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='user_fav', to='auctions.Listings'),
        ),
        migrations.DeleteModel(
            name='WatchlistItems',
        ),
    ]
