# Generated by Django 3.2 on 2021-05-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210524_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listings',
            new_name='listing',
        ),
    ]
